/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories"];
        put?: never;
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCategory"];
        post?: never;
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feedback/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/admin/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["words"];
        put?: never;
        post: operations["createWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/words/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateWord"];
        post?: never;
        delete: operations["deleteWord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mine"];
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{sessionId}/cards/{cardId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["answer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{sessionId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{sessionId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{sessionId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-words/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-words/csv/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-words/csv/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personal-words/csv/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/learning-goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateDailyGoal"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/practice-reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["practiceReminder"];
        put: operations["updatePracticeReminder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActiveGameSummary: {
            /** Format: int32 */
            answeredCards?: number;
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: int32 */
            totalCards?: number;
        };
        AdminFeedbackUpdate: {
            adminNote?: string | null;
            /** @enum {string} */
            status?: "OPEN" | "IN_REVIEW" | "RESOLVED" | "REJECTED";
        };
        AdminWordRequest: {
            categoryIds?: string[];
            english: string;
            german: string;
            perfectForm?: string | null;
            presentForm?: string | null;
            preteriteForm?: string | null;
        };
        AdminWordView: {
            categoryIds?: string[];
            english?: string;
            german?: string;
            /** Format: uuid */
            id?: string;
            perfectForm?: string | null;
            presentForm?: string | null;
            preteriteForm?: string | null;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        AnswerCardRequest: {
            /** @enum {string} */
            result?: "KNOWN" | "DIFFICULT";
        };
        AuditLogEntry: {
            action?: string;
            actorName?: string | null;
            /** Format: uuid */
            actorProfileId?: string | null;
            /** Format: uuid */
            correlationId?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            id?: string;
            metadata?: string;
            /** Format: uuid */
            targetId?: string | null;
            targetType?: string;
        };
        AuditLogPage: {
            items?: components["schemas"]["AuditLogEntry"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        CategoryRequest: {
            name: string;
            slug: string;
            /** Format: int32 */
            sortOrder?: number;
            type?: string;
        };
        CategorySummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** Format: int32 */
            wordCount?: number;
        };
        CategoryView: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** Format: int32 */
            sortOrder?: number;
            type?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CsvPreview: {
            /** Format: int32 */
            added?: number;
            rows?: components["schemas"]["CsvRowPreview"][];
            /** Format: int32 */
            skipped?: number;
            /** Format: int32 */
            updated?: number;
            valid?: boolean;
        };
        CsvRowPreview: {
            category?: string | null;
            english?: string;
            errors?: string[];
            german?: string;
            /** Format: int32 */
            row?: number;
            status?: string;
        };
        CurrentProfile: {
            /** Format: int32 */
            dailyGoalGames?: number;
            displayName?: string | null;
            /** Format: uuid */
            id?: string;
        };
        DailyGoalPreference: {
            /** Format: int32 */
            games?: number;
        };
        DailyGoalRequest: {
            /** Format: int32 */
            games?: number;
        };
        DailyLearningGoal: {
            achieved?: boolean;
            /** Format: int32 */
            completedGames?: number;
            /** Format: int32 */
            percentage?: number;
            /** Format: int32 */
            targetGames?: number;
        };
        DifficultWordSummary: {
            english?: string;
            german?: string;
            /** Format: uuid */
            id?: string;
            source?: string;
        };
        FeedbackRequest: {
            message: string;
            subject: string;
            /** @enum {string} */
            type?: "GENERAL" | "WORD_REPORT" | "TECHNICAL" | "FEATURE";
            /** Format: uuid */
            wordId?: string | null;
        };
        FeedbackView: {
            adminNote?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            id?: string;
            message?: string;
            /** @enum {string} */
            status?: "OPEN" | "IN_REVIEW" | "RESOLVED" | "REJECTED";
            subject?: string;
            /** @enum {string} */
            type?: "GENERAL" | "WORD_REPORT" | "TECHNICAL" | "FEATURE";
            /** Format: uuid */
            wordId?: string | null;
        };
        GameCard: {
            back?: string;
            forms?: string[];
            front?: string;
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            position?: number;
            /** @enum {string|null} */
            result?: "KNOWN" | "DIFFICULT" | null;
            source?: string;
            /** Format: uuid */
            wordId?: string;
        };
        GameSessionView: {
            /** Format: double */
            accuracy?: number | null;
            /** Format: int32 */
            answered?: number;
            cards?: components["schemas"]["GameCard"][];
            /** Format: int32 */
            difficult?: number;
            /** @enum {string} */
            direction?: "DE_EN" | "EN_DE";
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            known?: number;
            /** Format: uuid */
            rootSessionId?: string;
            status?: string;
            /** @enum {string} */
            type?: "ORIGINAL" | "REVIEW" | "REPLAY";
        };
        LearningActivity: {
            days?: components["schemas"]["LearningActivityDay"][];
            /** Format: int32 */
            gamesCompleted?: number;
            /** Format: int32 */
            gamesStarted?: number;
            /** Format: int32 */
            periodDays?: number;
        };
        LearningActivityDay: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            gamesCompleted?: number;
            /** Format: int32 */
            gamesStarted?: number;
        };
        PersonalWordRequest: {
            category?: string | null;
            english: string;
            german: string;
        };
        PersonalWordView: {
            category?: string | null;
            english?: string;
            german?: string;
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        PracticeReminderPreference: {
            enabled?: boolean;
            localTime?: string;
            timezone?: string;
        };
        PracticeReminderRequest: {
            enabled?: boolean;
            localTime?: string;
            timezone: string;
        };
        ProgressDashboard: {
            activeGame?: components["schemas"]["ActiveGameSummary"] | null;
            activity?: components["schemas"]["LearningActivity"];
            dailyGoal?: components["schemas"]["DailyLearningGoal"];
            difficultWords?: components["schemas"]["DifficultWordSummary"][];
            recentGames?: components["schemas"]["RecentGameSummary"][];
            summary?: components["schemas"]["ProgressSummary"];
        };
        ProgressSummary: {
            /** Format: double */
            accuracy?: number | null;
            /** Format: int32 */
            completedGames?: number;
            /** Format: int32 */
            currentStreakDays?: number;
            /** Format: int32 */
            difficultWords?: number;
            /** Format: int32 */
            exploredWords?: number;
            /** Format: int32 */
            knownWords?: number;
            /** Format: date-time */
            lastPractisedAt?: string | null;
        };
        RecentGameSummary: {
            /** Format: double */
            accuracy?: number | null;
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            totalCards?: number;
            type?: string;
        };
        ResetProgressRequest: {
            confirmed?: boolean;
            /** @enum {string} */
            type?: "UNSEEN_HISTORY" | "LEARNING_PROGRESS" | "ALL_PROGRESS";
        };
        ResetProgressResult: {
            /** Format: int32 */
            affectedRecords?: number;
            /** @enum {string} */
            type?: "UNSEEN_HISTORY" | "LEARNING_PROGRESS" | "ALL_PROGRESS";
        };
        StartGameRequest: {
            /** Format: int32 */
            cardCount?: number;
            categoryIds?: string[];
            /** @enum {string} */
            direction?: "DE_EN" | "EN_DE";
            /** @enum {string} */
            ordering?: "RANDOM" | "AZ";
            personalWordIds?: string[];
            unseenOnly?: boolean;
            wordIds?: string[];
        };
        WordSummary: {
            english?: string;
            forms?: string[];
            german?: string;
            /** Format: uuid */
            id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    find: {
        parameters: {
            query?: {
                action?: string;
                targetType?: string;
                actorProfileId?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditLogPage"];
                };
            };
        };
    };
    categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"];
                };
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryView"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queue: {
        parameters: {
            query?: {
                status?: "OPEN" | "IN_REVIEW" | "RESOLVED" | "REJECTED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackView"][];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminFeedbackUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackView"];
                };
            };
        };
    };
    words: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminWordView"][];
                };
            };
        };
    };
    createWord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminWordRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminWordView"];
                };
            };
        };
    };
    updateWord: {
        parameters: {
            query?: never;
            header: {
                "If-Match": number;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminWordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminWordView"];
                };
            };
        };
    };
    deleteWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackView"][];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackView"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartGameRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameSessionView"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameSessionView"];
                };
            };
        };
    };
    answer: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                sessionId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerCardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameSessionView"];
                };
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameSessionView"];
                };
            };
        };
    };
    replay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameSessionView"];
                };
            };
        };
    };
    review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameSessionView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalWordView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalWordRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalWordView"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header: {
                "If-Match": number;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalWordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalWordView"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsvPreview"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsvPreview"];
                };
            };
        };
    };
    current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentProfile"];
                };
            };
        };
    };
    updateDailyGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyGoalRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DailyGoalPreference"];
                };
            };
        };
    };
    practiceReminder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PracticeReminderPreference"];
                };
            };
        };
    };
    updatePracticeReminder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeReminderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PracticeReminderPreference"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgressDashboard"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetProgressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResetProgressResult"];
                };
            };
        };
    };
    categories_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategorySummary"][];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WordSummary"][];
                };
            };
        };
    };
}
