"use client";
import { FormEvent, useEffect, useState } from "react";
type Word={id:string;german:string;english:string;category:string|null;version:number};
type Preview={valid:boolean;added:number;updated:number;skipped:number};
export default function WordsClient(){
 const[words,setWords]=useState<Word[]>([]),[csv,setCsv]=useState("german,english,category\nabfahren,to depart,My verbs"),[preview,setPreview]=useState<Preview|null>(null),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/personal-words");if(r.ok)setWords(await r.json())}useEffect(()=>{load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form),r=await fetch("/api/personal-words",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({german:data.get("german"),english:data.get("english"),category:data.get("category")})});if(r.ok){form.reset();setMessage("Word added.");await load()}else setMessage((await r.json()).detail??"Could not add word.")}
 async function remove(word:Word){if(!confirm(`Delete ${word.german}?`))return;const r=await fetch(`/api/personal-words/${word.id}`,{method:"DELETE"});if(r.ok)await load()}
 async function practise(){const selected=words.slice(0,Math.min(20,words.length));const r=await fetch("/api/games",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personalWordIds:selected.map(w=>w.id),cardCount:selected.length,direction:"DE_EN",ordering:"RANDOM"})}),body=await r.json();if(r.ok)location.href=`/play?session=${body.id}`;else setMessage(body.detail??"Could not start a personal-word game.")}
 async function check(){const r=await fetch("/api/personal-words/csv/preview",{method:"POST",headers:{"Content-Type":"text/csv"},body:csv}),body=await r.json();if(r.ok)setPreview(body);else setMessage(body.detail??"CSV could not be validated.")}
 async function apply(){const r=await fetch("/api/personal-words/csv/import",{method:"POST",headers:{"Content-Type":"text/csv"},body:csv});if(r.ok){setMessage("CSV imported.");setPreview(null);await load()}}
 return <main className="words-shell"><header><a className="brand" href="/">Wörter<span>See</span></a><nav><a href="/play">Play</a><a href="/api/personal-words/csv/export">Export CSV</a></nav></header><section className="words-intro"><p className="eyebrow">MY WORDS</p><h1>Your own vocabulary,<br/>ready to practise.</h1><button className="primary" disabled={!words.length} onClick={practise}>Practise my words</button></section><section className="words-grid"><div><h2>Add a word</h2><form className="word-form" onSubmit={add}><label>German<input name="german" required maxLength={255}/></label><label>English<input name="english" required maxLength={255}/></label><label>Category<input name="category" maxLength={140}/></label><button className="primary">Add word</button></form>{message&&<p aria-live="polite">{message}</p>}</div><div><h2>{words.length} saved words</h2><div className="word-list">{words.map(word=><article key={word.id}><div><strong>{word.german}</strong><span>{word.english}{word.category?` · ${word.category}`:""}</span></div><button onClick={()=>remove(word)}>Delete</button></article>)}</div></div></section><section className="csv-panel"><div><p className="eyebrow">CSV IMPORT</p><h2>Preview before anything changes.</h2><p>Required headers: german, english, category.</p></div><div><textarea value={csv} onChange={e=>setCsv(e.target.value)} rows={8}/><div className="csv-actions"><button className="secondary" onClick={check}>Validate CSV</button>{preview?.valid&&<button className="primary" onClick={apply}>Import {preview.added+preview.updated} rows</button>}</div>{preview&&<p>{preview.added} added · {preview.updated} updated · {preview.skipped} skipped</p>}</div></section></main>
}
