package de.woertersee.api.admin.vocabulary
import de.woertersee.api.platform.error.ConflictException
import de.woertersee.api.platform.error.NotFoundException
import org.slf4j.MDC
import org.springframework.dao.DuplicateKeyException
import org.springframework.jdbc.core.simple.JdbcClient
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.sql.Types
import java.util.UUID
@Service class AdminVocabularyService(private val jdbc:JdbcClient){
 fun words(query:String)=jdbc.sql("""SELECT id,german,english,present_form,preterite_form,perfect_form,version,updated_at FROM words
  WHERE deleted_at IS NULL AND (:query='' OR normalized_german LIKE lower(:query)||'%' OR lower(english) LIKE '%'||lower(:query)||'%') ORDER BY normalized_german LIMIT 200""")
  .param("query",query.trim()).query{rs,_->mapWord(rs)}.list()
 @Transactional fun createWord(admin:UUID,request:AdminWordRequest):AdminWordView{val id=UUID.randomUUID();try{jdbc.sql("""INSERT INTO words(id,german,english,normalized_german,present_form,preterite_form,perfect_form)
  VALUES(:id,:de,:en,:normalized,:present,:preterite,:perfect)""").param("id",id).bindWord(request).update()}catch(e:DuplicateKeyException){throw ConflictException("A matching global word already exists")};replaceCategories(id,request.categoryIds);audit(admin,"GLOBAL_WORD_CREATED","word",id);outbox("WordCorrected",id,admin);return word(id)}
 @Transactional fun updateWord(admin:UUID,id:UUID,version:Long,request:AdminWordRequest):AdminWordView{val count=try{jdbc.sql("""UPDATE words SET german=:de,english=:en,normalized_german=:normalized,present_form=:present,preterite_form=:preterite,perfect_form=:perfect,
  version=version+1,updated_at=now() WHERE id=:id AND version=:version AND deleted_at IS NULL""").param("id",id).param("version",version).bindWord(request).update()}catch(e:DuplicateKeyException){throw ConflictException("A matching global word already exists")};if(count==0)throw ConflictException("Word changed or no longer exists");replaceCategories(id,request.categoryIds);audit(admin,"GLOBAL_WORD_UPDATED","word",id);outbox("WordCorrected",id,admin);return word(id)}
 @Transactional fun deleteWord(admin:UUID,id:UUID){if(jdbc.sql("UPDATE words SET deleted_at=now(),updated_at=now(),version=version+1 WHERE id=:id AND deleted_at IS NULL").param("id",id).update()==0)throw NotFoundException("Word not found");audit(admin,"GLOBAL_WORD_DELETED","word",id);outbox("WordCorrected",id,admin)}
 fun categories()=jdbc.sql("SELECT id,name,slug,type,sort_order,updated_at FROM categories WHERE deleted_at IS NULL ORDER BY sort_order,name").query{rs,_->CategoryView(rs.getObject("id",UUID::class.java),rs.getString("name"),rs.getString("slug"),rs.getString("type"),rs.getInt("sort_order"),rs.getTimestamp("updated_at").toInstant())}.list()
 @Transactional fun createCategory(admin:UUID,request:CategoryRequest):CategoryView{val id=UUID.randomUUID();try{jdbc.sql("INSERT INTO categories(id,slug,name,type,sort_order) VALUES(:id,:slug,:name,:type,:sort)").param("id",id).bindCategory(request).update()}catch(e:DuplicateKeyException){throw ConflictException("Category slug already exists")};audit(admin,"CATEGORY_CREATED","category",id);return category(id)}
 @Transactional fun updateCategory(admin:UUID,id:UUID,request:CategoryRequest):CategoryView{try{if(jdbc.sql("UPDATE categories SET slug=:slug,name=:name,type=:type,sort_order=:sort,updated_at=now() WHERE id=:id AND deleted_at IS NULL").param("id",id).bindCategory(request).update()==0)throw NotFoundException("Category not found")}catch(e:DuplicateKeyException){throw ConflictException("Category slug already exists")};audit(admin,"CATEGORY_UPDATED","category",id);return category(id)}
 @Transactional fun deleteCategory(admin:UUID,id:UUID){if(jdbc.sql("UPDATE categories SET deleted_at=now(),updated_at=now() WHERE id=:id AND deleted_at IS NULL").param("id",id).update()==0)throw NotFoundException("Category not found");audit(admin,"CATEGORY_DELETED","category",id)}
 private fun word(id:UUID)=jdbc.sql("SELECT id,german,english,present_form,preterite_form,perfect_form,version,updated_at FROM words WHERE id=:id AND deleted_at IS NULL").param("id",id).query{rs,_->mapWord(rs)}.optional().orElseThrow{NotFoundException("Word not found")}
 private fun mapWord(rs:java.sql.ResultSet):AdminWordView{val id=rs.getObject("id",UUID::class.java);val ids=jdbc.sql("SELECT category_id FROM word_categories WHERE word_id=:id").param("id",id).query(UUID::class.java).list().filterNotNull().toSet();return AdminWordView(id,rs.getString("german"),rs.getString("english"),rs.getString("present_form"),rs.getString("preterite_form"),rs.getString("perfect_form"),rs.getLong("version"),ids,rs.getTimestamp("updated_at").toInstant())}
 private fun category(id:UUID)=categories().firstOrNull{it.id==id}?:throw NotFoundException("Category not found")
 private fun replaceCategories(wordId:UUID,ids:Set<UUID>){if(ids.isNotEmpty()){val found=jdbc.sql("SELECT count(*) FROM categories WHERE id IN (:ids) AND deleted_at IS NULL").param("ids",ids).query(Int::class.java).single();require(found==ids.size){"One or more categories do not exist"}};jdbc.sql("DELETE FROM word_categories WHERE word_id=:id").param("id",wordId).update();ids.forEach{jdbc.sql("INSERT INTO word_categories(word_id,category_id) VALUES(:wordId,:categoryId)").param("wordId",wordId).param("categoryId",it).update()}}
 private fun JdbcClient.StatementSpec.bindWord(r:AdminWordRequest)=param("de",r.german.trim()).param("en",r.english.trim()).param("normalized",r.german.trim().lowercase()).param("present",r.presentForm?.trim(),Types.VARCHAR).param("preterite",r.preteriteForm?.trim(),Types.VARCHAR).param("perfect",r.perfectForm?.trim(),Types.VARCHAR)
 private fun JdbcClient.StatementSpec.bindCategory(r:CategoryRequest)=param("slug",r.slug.trim().lowercase()).param("name",r.name.trim()).param("type",r.type.uppercase()).param("sort",r.sortOrder)
 private fun audit(actor:UUID,action:String,target:String,id:UUID){val correlation=runCatching{UUID.fromString(MDC.get("correlation_id"))}.getOrNull();jdbc.sql("INSERT INTO audit_logs(id,actor_profile_id,action,target_type,target_id,correlation_id) VALUES(:id,:actor,:action,:target,:targetId,:correlation)").param("id",UUID.randomUUID()).param("actor",actor).param("action",action).param("target",target).param("targetId",id).param("correlation",correlation,Types.OTHER).update()}
 private fun outbox(type:String,id:UUID,user:UUID){val correlation=runCatching{UUID.fromString(MDC.get("correlation_id"))}.getOrElse{UUID.randomUUID()};jdbc.sql("""INSERT INTO outbox_events(event_id,event_type,event_version,aggregate_id,user_id,occurred_at,correlation_id,payload)
  VALUES(:eventId,:type,1,:id,:user,now(),:correlation,jsonb_build_object('word_id',:id))""").param("eventId",UUID.randomUUID()).param("type",type).param("id",id).param("user",user).param("correlation",correlation).update()}
}
