"use client";
import { useEffect, useState } from "react";
type Word={id:string};
type Card={id:string;wordId:string;source:"GLOBAL"|"PERSONAL";front:string;back:string;forms:string[];result:"KNOWN"|"DIFFICULT"|null};
type Game={id:string;status:string;cards:Card[];answered:number;known:number;difficult:number;accuracy:number|null};
export default function PlayClient({userName}:{userName:string}){
 const[words,setWords]=useState<Word[]>([]),[game,setGame]=useState<Game|null>(null),[index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{const session=new URLSearchParams(location.search).get("session");if(session){fetch(`/api/games/${session}`).then(async r=>{if(!r.ok)throw 0;return r.json()}).then(setGame).catch(()=>setError("The saved game is unavailable."));return}fetch("/api/vocabulary").then(async r=>{if(!r.ok)throw 0;return r.json()}).then(setWords).catch(()=>setError("The vocabulary catalogue is unavailable."))},[]);
 const current=game?.cards[index];
 async function start(){const r=await fetch("/api/games",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({wordIds:words.slice(0,10).map(w=>w.id),cardCount:10,direction:"DE_EN",ordering:"RANDOM"})}),body=await r.json();if(!r.ok)return setError(body.detail??"Could not start a game.");setGame(body);setIndex(0)}
 async function answer(result:"KNOWN"|"DIFFICULT"){if(!game||!current)return;const r=await fetch(`/api/games/${game.id}/cards/${current.id}/answer`,{method:"PUT",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({result})}),body=await r.json();if(!r.ok)return setError(body.detail??"Could not save the answer.");setGame(body);setRevealed(false);if(index<body.cards.length-1)setIndex(index+1);else await action("finish",body.id)}
 async function action(name:"finish"|"review"|"replay",id=game?.id){if(!id)return;const r=await fetch(`/api/games/${id}/${name}`,{method:"POST"}),body=await r.json();if(!r.ok)return setError(body.detail??"Action failed.");setGame(body);setIndex(0);setRevealed(false)}
 async function report(){if(!current||current.source!=="GLOBAL")return;const message=prompt("What should be corrected about this word?");if(!message)return;const r=await fetch("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"WORD_REPORT",wordId:current.wordId,subject:`Word report: ${current.front}`,message})});setNotice(r.ok?"Report sent to the admin queue.":"Report could not be sent.")}
 if(!game)return <main className="play-shell"><header><a className="brand" href="/">Wörter<span>See</span></a><span>Hello, {userName}</span></header><section className="start-panel"><p className="eyebrow">QUICK PLAY</p><h1>Ready for ten words?</h1><p>{words.length?`${words.length} words are available.`:"Loading your catalogue…"}</p><button className="primary" disabled={!words.length} onClick={start}>Continue unseen →</button>{error&&<p role="alert" className="error">{error}</p>}</section></main>;
 if(game.status!=="ACTIVE")return <main className="play-shell"><header><a className="brand" href="/">Wörter<span>See</span></a><span>Game complete</span></header><section className="results"><p className="eyebrow">SESSION COMPLETE</p><h1>{game.accuracy?.toFixed(0)??"—"}%</h1><p>{game.answered} answered · {game.known} known · {game.difficult} difficult</p><div className="actions"><button className="primary" disabled={!game.difficult} onClick={()=>action("review")}>Review my mistakes</button><button className="secondary" onClick={()=>action("replay")}>Replay original deck</button><a href="/">Back to home</a></div>{error&&<p className="error">{error}</p>}</section></main>;
 return <main className="play-shell"><header><a className="brand" href="/">Wörter<span>See</span></a><span>{index+1} / {game.cards.length}</span></header><div className="progress"><i style={{width:`${((index+(current?.result?1:0))/game.cards.length)*100}%`}}/></div><section className="card-stage"><div className="word-card" onClick={()=>setRevealed(true)} role="button" tabIndex={0} onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&setRevealed(true)}><p>{revealed?"TRANSLATION":"GERMAN"}</p><h1>{revealed?current?.back:current?.front}</h1>{!revealed&&current?.forms.length?<span>{current.forms.join(" · ")}</span>:null}<small>{revealed?"How did that feel?":"Tap to reveal"}</small></div>{current?.source==="GLOBAL"&&<button className="finish" onClick={report}>Report this word</button>}{notice&&<p>{notice}</p>}{revealed&&<div className="answer-actions"><button onClick={()=>answer("DIFFICULT")}>Not yet</button><button onClick={()=>answer("KNOWN")}>Got it</button></div>}<button className="finish" onClick={()=>action("finish")}>Finish game</button>{error&&<p className="error">{error}</p>}</section></main>
}
